# Generated by Django 4.1.3 on 2022-11-28 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0005_user_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
