# Generated by Django 4.1.3 on 2022-12-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0015_alter_user_gym_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_gym',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
