# Generated by Django 4.1.3 on 2022-12-05 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0020_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='program_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tola.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
