# Generated by Django 4.1.3 on 2022-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0023_program_session_exercise_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_session_exercise_set',
            name='set_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
