# Generated by Django 4.1.3 on 2022-12-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0025_rename_program_session_program_session_exercise_set_program_session_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_session_exercise_set',
            name='athlete',
        ),
        migrations.CreateModel(
            name='user_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tola.program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
