# Generated by Django 4.1.3 on 2022-12-06 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0028_remove_program_session_day_program_session_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_session_exercise',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
