# Generated by Django 4.1.3 on 2022-11-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0012_alter_exercise_name_alter_max_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='max',
            unique_together=set(),
        ),
    ]
