# Generated by Django 4.1.3 on 2022-12-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0013_alter_max_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_gym',
            unique_together={('user', 'gym', 'active')},
        ),
    ]
