# Generated by Django 4.1.3 on 2022-12-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0018_alter_exercise_created_at_alter_exercise_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='max',
            unique_together=set(),
        ),
    ]
