# Generated by Django 4.1.3 on 2022-12-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0021_program_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='program_session_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise', to='tola.exercise')),
                ('max_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='max_exercise', to='tola.exercise')),
                ('program_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tola.program_session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
