# Generated by Django 4.1.3 on 2022-12-06 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0026_remove_program_session_exercise_set_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_session',
            name='week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user_program',
            unique_together={('athlete', 'program', 'active')},
        ),
    ]
