# Generated by Django 4.1.3 on 2022-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0030_setstatus_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='units',
            field=models.BooleanField(default=False),
        ),
    ]
