# Generated by Django 4.1.3 on 2022-12-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0031_customuser_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_session_exercise_set',
            name='num_of_reps',
            field=models.CharField(max_length=6),
        ),
    ]
