# Generated by Django 4.1.3 on 2023-02-22 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola', '0032_alter_program_session_exercise_set_num_of_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='program_session_exercise_set',
            name='num_of_reps',
            field=models.CharField(max_length=100),
        ),
    ]
